version: '3'
services:
  java-RestApi:
    image: java-rest-api:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "2020:8080"
    volumes:
      - ./DataSet:/app/DataSet
    restart: always
